info:
  name: config_file_scan
  author: Manushya-a
  severity: 3
  description: Configuration file finder
  reference:
  profiles:
    - scan
    - http
    - backup
    - low_severity

payloads:
  - library: http
    steps:
      - method: get
        timeout: 3
        headers:
          User-Agent: "{user_agent}"
        allow_redirects: false
        ssl: false
        url:
          nettacker_fuzzer:
            input_format: "{{schema}}://{target}:{{ports}}/{url_base_path}{{urls}}"
            prefix: ""
            suffix: ""
            interceptors:
            data:
              urls:
                read_from_file: wordlists/config_wordlist.txt
              schema:
                - "http"
                - "https"
              ports:
                - 80
                - 443
        response:
          condition_type: and
          log: "response_dependent['url']"
          conditions:
            url:
              regex: .*
              reverse: false 
            status_code:
              regex: 200|403|401
              reverse: false
