#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Pradeep Jairamani , github.com/pradeepjairamani


def wp_plugins():
    return ["1-flash-gallery", "1-jquery-photo-gallery-slideshow-flash", "Calendar", "Premium_Gallery_Manager",
            "a-gallery", "a-to-z-category-listing", "accept-signups", "adminimize", "adrotate", "advanced-text-widget",
            "advertizer", "age-verification", "ajax-category-dropdown", "ajax-store-locator-wordpress_0", "ajaxgallery",
            "akismet", "alert-before-your-post", "all-in-one-wp-security-and-firewall", "all-video-gallery",
            "allwebmenus-wordpress-menu-plugin", "annonces", "announcement-and-vertical-scroll-news", "asset-manager",
            "audio", "auto-attachments", "backwpup", "bbpress", "bezahlcode-generator", "booking",
            "cac-featured-content", "catalog", "category-grid-view-gallery", "category-list-portfolio-page",
            "cevhershare", "cforms", "cforms2", "cimy-counter", "clickdesk-live-support-chat", "cm-download-manager",
            "cms-pack", "comicpress-manager", "comment-rating", "community-events", "complete-gallery-manager",
            "contact-form-wordpress", "contus-hd-flv-player", "contus-video-gallery", "copyright-licensing-tools",
            "count-per-day", "couponer", "cpl", "crawlrate-tracker", "custom-content-type-manager",
            "daily-maui-photo-widget", "db-backup", "disclosure-policy-plugin", "dm-albums", "dmsguestbook",
            "downloads-manager", "dp-thumbnail", "drag-drop-file-uploader", "dzs-videogallery",
            "easy-contact-form-lite", "easy-contact-forms-exporter", "editormonkey", "evarisk", "event-registration",
            "eventify", "extend-wordpress", "facebook-opengraph-meta-plugin", "fbpromotions", "fcchat",
            "feature-slideshow", "featurific-for-wordpress", "feedlist", "fgallery", "file-groups", "filedownload",
            "firestats", "flash-album-gallery", "flexible-custom-post-type", "font-uploader", "formcraft",
            "forum-server", "foxypress", "front-end-upload", "front-file-manager", "fs-real-estate-plugin",
            "gallery-images", "gallery-plugin", "gd-star-rating", "global-content-blocks", "google-document-embedder",
            "google-mp3-audio-player", "grapefile", "hd-webplayer", "html5avmanager", "igit-posts-slider-widget",
            "image-gallery-with-slideshow", "inboundio-marketing", "inline-gallery", "ip-logger", "is-human", "islidex",
            "iwant-one-ihave-one", "jetpack", "jquery-mega-menu", "jrss-widget", "js-appointment", "kino-gallery",
            "kish-guest-posting", "knr-author-list-widget", "lanoba-social-plugin", "lazy-seo", "lazyest-gallery",
            "leaguemanager", "like-dislike-counter-for-posts-pages-and-comments", "link-library",
            "lisl-last-image-slider", "livesig", "login-lockdown", "mac-dock-gallery", "mailz",
            "media-library-categories", "meenews", "mingle-forum", "mm-forms-community", "myflash", "mystat",
            "nextgen-gallery", "nextgen-smooth-gallery", "odihost-newsletter-plugin", "old-post-spinner",
            "omni-secure-files", "oqey-gallery", "oqey-headers", "page-flip-image-gallery", "paid-downloads",
            "photoracer", "photosmash-galleries", "php_speedy_wp", "pica-photo-gallery", "pictpress", "placester",
            "plugin-dir", "plugin-newsletter", "post-highlights", "premium_gallery_manager", "pretty-link", "profiles",
            "proplayer", "pure-html", "radykal-fancy-gallery", "rating-widget", "rbxgallery", "really-easy-slider",
            "recipe", "reciply", "reflex-gallery", "rekt-slideshow", "related-sites", "relocate-upload", "rent-a-car",
            "resume-submissions-job-postings", "ripe-hd-player", "rss-feed-reader", "scormcloud", "search-autocomplete",
            "sendit", "seo-automatic-seo-tools", "sermon-browser", "sexy-contact-form", "sfbrowser", "sh-slideshow",
            "si-contact-form", "simple-download-button-shortcode", "skysa-official", "sniplets", "social-discussions",
            "social-slider-2", "sodahead-polls", "sp-client-document-manager", "spicy-blogroll",
            "spider-event-calendar", "st_newsletter", "statpress", "stats", "store-locator-le", "subscribe-to-comments",
            "tagninja", "the-welcomizer", "thecartpress", "thinkun-remind", "tinymce-thumbnail-gallery", "topquark",
            "tune-library", "ucan-post", "ungallery", "uploader", "uploads", "upm-polls", "user-avatar", "user-meta",
            "verve-meta-boxes", "videowhisper-live-streaming-integration", "videowhisper-video-presentation",
            "vk-gallery", "vodpod-video-gallery", "wassup", "webinar_plugin", "website-faq",
            "wordpress-donation-plugin-with-goals-and-paypal-ipn-by-nonprofitcmsorg", "wordpress-processing-embed",
            "wordtube", "wp-adserve", "wp-audio-gallery-playlist", "wp-automatic", "wp-autoyoutube", "wp-bannerize",
            "wp-cal", "wp-content", "wp-cumulus", "wp-custom-pages", "wp-db-backup", "wp-ds-faq", "wp-e-commerce",
            "wp-easycart", "wp-featured-post-with-thumbnail", "wp-filebase", "wp-filemanager", "wp-footnotes",
            "wp-forum", "wp-glossary", "wp-gpx-maps", "wp-lytebox", "wp-marketplace", "wp-menu-creator", "wp-people",
            "wp-property", "wp-publication-archive", "wp-realty", "wp-safe-search", "wp-shopping-cart", "wp-spamfree",
            "wp-starsratebox", "wp-stats-dashboard", "wp-support-plus-responsive-ticket-system",
            "wp-survey-and-quiz-tool", "wp-symposium", "wp-syntax", "wp-table", "wp-twitter-feed", "wp-whois", "wpSS",
            "wpeasystats", "wpforum", "wpmarketplace", "wpstorecart", "wptouch", "x7host-videox7-ugc-plugin",
            "yolink-search", "yt-audio-streaming-audio-from-youtube", "zingiri-web-shop", "zotpress",
            "zotpressinboundio-marketing"]
