# -*- coding: utf-8 -*-
def takeovers():
    return {
        "sub_takeover_aws": ["The specified bucket does not exist"],
        "sub_takeover_bitbucket": ["Repository not found|The page you have requested does not exist"],
        "sub_takeover_github": ["There isn't a Github Pages site here.|For root URLs (like http://example.com/) you must provide an index.html file"],
        "sub_takeover_shopify": ["Sorry, this shop is currently unavailable."],
        "sub_takeover_fastly": ["Fastly error: unknown domain:"],
        "sub_takeover_feedPress": ["The feed has not been found."],
        "sub_takeover_ghost": ["The thing you were looking for is no longer here, or never was|The thing you were looking for is no longer here"],
        "sub_takeover_heroku": ["no-such-app.html|<title>no such app</title>|herokucdn.com/error-pages/no-such-app.html"],
        "sub_takeover_uberflip": ['"Non-hub domain, The URL you\'ve accessed does not provide a hub."'],
        "sub_takeover_hubspot": ["Domain not found|does not exist in our system"],
        "sub_takeover_pantheon": ["The gods are wise, but do not know of the site which you seek."],
        "sub_takeover_tumblr": ["Whatever you were looking for doesn't currently exist at this address.|There's nothing here."],
        "sub_takeover_worksites": ['"(?:Company Not Found|you&rsquo;re looking for doesn&rsquo;t exist)"'],
        "sub_takeover_wufoo": ["Profile not found|Hmmm....something is not right."],
        "sub_takeover_wordpress": ["Do you want to register"],
        "sub_takeover_teamWork": ["Oops - We didn't find your site."],
        "sub_takeover_helpjuice": ["We could not find what you're looking for."],
        "sub_takeover_helpscout": ["No settings were found for this company:"],
        "sub_takeover_cargo": ["<title>404 &mdash; File not found</title>|If you're moving your domain away from Cargo you must make this configuration through your registrar's DNS control panel."],
        "sub_takeover_statusPage": ['You are being <a href="https://www.statuspage.io">redirected'],
        "sub_takeover_frontify": ['404 - Page Not Found|Oops… looks like you got lost'],
        "sub_takeover_cargocollective": ['<div class="notfound">|404 Not Found<br>'],
        "sub_takeover_uservoice": ["This UserVoice subdomain is currently available!"],
        "sub_takeover_surge": ["project not found"],
        "sub_takeover_intercom": ['This page is reserved for artistic dogs.|<h1 class="headline">Uh oh. That page doesn’t exist.</h1>'],
        "sub_takeover_webflow": ['<p class="description">The page you are looking for doesn\'t exist or has been moved.</p>'],
        "sub_takeover_kajabi": ["<h1>The page you were looking for doesn't exist.</h1>"],
        "sub_takeover_thinkific": ["You may have mistyped the address or the page may have moved."],
        "sub_takeover_tave": ["<h1>Error 404: Page Not Found</h1>"],
        "sub_takeover_wishpond": ["<h1>https://www.wishpond.com/404?campaign=true"],
        "sub_takeover_aftership": ["Oops.</h2><p class=\"text-muted text-tight\">The page you're looking for doesn't exist."],
        "sub_takeover_aha": ["There is no portal here ... sending you back to Aha!"],
        "sub_takeover_tictail": ['to target URL: <a href="https://tictail.com|Start selling on Tictail.|Building a brand of your own?|Start selling on Tictail.'],
        "sub_takeover_brightcove": ['<p class="bc-gallery-error-code">Error Code: 404</p>'],
        "sub_takeover_bigcartel": ["<h1>Oops! We couldn&#8217;t find that page.</h1>"],
        "sub_takeover_canny": ["Company Not Found|There is no such company. Did you enter the right URL?"],
        "sub_takeover_activeCampaign": ['alt="LIGHTTPD - fly light."'],
        "sub_takeover_campaignmonitor": ['or <a href="mailto:help@createsend.com|<strong>Trying to access your account?</strong>'],
        "sub_takeover_acquia": ["The site you are looking for could not be found.|If you are an Acquia Cloud customer and expect to see your site at this address"],
        "sub_takeover_proposify": ['If you need immediate assistance, please contact <a href="mailto:support@proposify.biz"'],
        "sub_takeover_simplebooklet": ["We can't find this <a href=\"https://simplebooklet.com"],
        "sub_takeover_getResponse": ["With GetResponse Landing Pages, lead generation has never been easier"],
        "sub_takeover_vend": ["Looks like you've traveled too far into cyberspace."],
        "sub_takeover_jetbrains": ["is not a registered InCloud YouTrack."],
        "sub_takeover_smartling": ["Domain is not configured"],
        "sub_takeover_pingdom": ["Public Report Not Activated|This public report page has not been activated by the user"],
        "sub_takeover_tilda": ["Domain has been assigned|<title>Please renew your subscription</title>|Please go to the site settings and put the domain name in the Domain tab."],
        "sub_takeover_surveygizmo": ["data-html-name"],
        "sub_takeover_mashery": ["Unrecognized domain <strong>"],
        "sub_takeover_divio": ["Application not responding"],
        "sub_takeover_airee": ["Ошибка 402. Сервис Айри.рф не оплачен"],
        "sub_takeover_anima": ["If this is your website and you've just created it, try refreshing in a minute"],
        "sub_takeover_readthedocs": ["unknown to Read the Docs"],
        "sub_takeover_zendesk": ["this help center no longer exists"],
        "sub_takeover_hatenablog": ["404 Blog is not found|Sorry, we can't find the page you're looking for."],
        "sub_takeover_kinsta": ["No Site For Domain"],
        "sub_takeover_launchrock": ["It looks like you may have taken a wrong turn somewhere. Don't worry...it happens to all of us."],
        "sub_takeover_ngrok": ["Tunnel *.ngrok.io not found|ngrok.io not found"],
        "sub_takeover_unbounce": ["The requested URL was not found on this server."],
        "sub_takeover_readme": ["Project doesnt exist... yet!"],
        "sub_takeover_smartjobboard": ["This job board website is either expired or its domain name is invalid.|Job Board Is Unavailable|This job board website is either expired"],
        "sub_takeover_jazzhr": ["This account no longer active"],
        "sub_takeover_uptimerobot": ['"^page not found$"'],
        "sub_takeover_helprace": ['Alias not configured!|Admin of this Helprace account needs to set up domain alias|"(see Step 2 here: Using your own domain with Helprace)."'],
        "sub_takeover_vercel": ["The deployment could not be found on Vercel.|DEPLOYMENT_NOT_FOUND"],
        "sub_takeover_netlify": ['"Not Found"|"server: Netlify"'],
        "sub_takeover_strikingly": ["But if you're looking to build your own website|you've come to the right place."],
        "sub_takeover_agilecrm": ["Sorry, this page is no longer available."],
        "sub_takeover_gemfury": ["404: This page could not be found."],
        "sub_takeover_getresponse": ["With GetResponse Landing Pages, lead generation has never been easier"],
        "sub_takeover_juzzhr": ["This account no longer active"],
        "sub_takeover_landingi": ["The page you are looking for is not found|It looks like you're lost"],
        "sub_takeover_smugmug": ["{\"text\":\"Page Not Found\""]
    }
